title: Open Horizon
description: An Open Source Project for secure and robust containerized application management for constrained devices.
theme: jekyll-theme-tactile


# Secondary Parameters
# baseurl: "/toc-avm/avm"
header-img: img/hero-dark.jpg
headercolor: "#FFFFFF"
logo: img/logos/open-horizon.png